# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Model-based variance estimator for an estimated population total
#'
#' @param cov Model parameter covariance matrix
#' @param X Design matrix
#' @return The variance estimate
#'
#' @export
est_var_mb <- function(cov, X) {
    .Call('restimate_est_var_mb', PACKAGE = 'restimate', cov, X)
}

#' Return the sum of squared estimated residuals when two OLS models are
#' applied in model-based inference
#'
#' @param X Design matrix of the first model for the first-phase sample
#' @param Z Design matrix of the second model for the first-phase sample
#' @param beta Parameter estimates of the first model (column vector)
#' @param alpha Parameter estimates of the second model (column vector)
#' @param vcov_beta Variance/co-variance matrix of first-model parameters
#'   estimates
#' @return The residual sum of squares
#'
#' @export
res_ss_tm <- function(X, Z, beta, alpha, vcov_beta) {
    .Call('restimate_res_ss_tm', PACKAGE = 'restimate', X, Z, beta, alpha, vcov_beta)
}

#' Estimated model parameter covariance matrix for the top-level model in
#' hierarchical model-based inference setting when two models are applied
#'
#' @param Z Design matrix of the second model for the first-phase sample
#' @param res Sum of squared residuals for the top-level model
#' @return Estimated covariance matrix for model parameter estimates
#'
#' @export
vcov_tm <- function(Z, ss_res) {
    .Call('restimate_vcov_tm', PACKAGE = 'restimate', Z, ss_res)
}

#' Return the squared estimated residuals when two OLS models are
#' applied in model-based inference and heteroscedasticity is present
#'
#' @param X Design matrix of the first model for the first-phase sample
#' @param Z Design matrix of the second model for the first-phase sample
#' @param beta Parameter estimates of the first model (column vector)
#' @param alpha Parameter estimates of the second model (column vector)
#' @param vcov_beta_hc Variance/co-variance matrix of first-model parameters
#'   estimates
#' @return The residual sum of squares
#'
#' @export
res_ss_hc_tm <- function(X, Z, beta, alpha, vcov_beta_hc) {
    .Call('restimate_res_ss_hc_tm', PACKAGE = 'restimate', X, Z, beta, alpha, vcov_beta_hc)
}

#' Estimated model parameter covariance matrix for the top-level model in
#' hierarchical model-based inference setting when two models are applied
#'
#' @param Z Design matrix of the second model for the first-phase sample
#' @param res Sum of squared residuals for the top-level model
#'
#' @details The heteroskedasticity-consistent version
#'
#' @return Estimated covariance matrix for model parameter estimates
#'
#' @export
vcov_tm_hc <- function(res_sq, X) {
    .Call('restimate_vcov_tm_hc', PACKAGE = 'restimate', res_sq, X)
}

